-- liquibase formatted sql
-- changeset linhdx:0.7.0
CREATE TABLE Orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        customer_name VARCHAR (500),
                        status        INT
);
INSERT INTO public.orders (id, customer_name, status) VALUES (1, 'customer 1', 1);
INSERT INTO public.orders (id, customer_name, status) VALUES (2, 'customer 2', 1);